name: Build test

on:
  create:
    branches:
  push:
    branches: [ main, dev, release/* ]
  pull_request:
    branches: [ main, dev, release/* ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install huggingface_hub
    - name: Download from HuggingFace datasets
      run: |
        huggingface-cli login --token ${{ secrets.HUGGING_FACE_SECRET }}
        huggingface-cli download retarfi/economy-watchers-survey --local-dir hf --local-dir-use-symlinks=False --repo-type dataset
    - uses: actions/checkout@v4
    - name: Build test
      run: |
        sudo apt install -y jq
        bash utils/build.sh