name: Bump version

on:
  create:
  workflow_dispatch:

jobs:
  makepr:
    name: Make PR
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'release/') }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install poetry
      run: pip install poetry
    - name: Bump version
      run: git branch --show-current | sed 's|release/||' | xargs poetry version | { printf '::set-output name=PR_TITLE::'; cat; }
      id: bump
    - name: Bump version 2
      run:  git branch --show-current | sed 's|release/||' | xargs -I {} echo '__version__ = "{}"' > ./src/economy_watchers_survey/version.py
    - name: Commit & Push
      run: |
        set -x
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit --author='GitHub Actions <action@github.com>' -m '${{ steps.bump.outputs.PR_TITLE }}'
        git push origin HEAD
    - name: Create pull request
      run: |
        echo ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
        gh pr create -B "main" -t "${{ steps.bump.outputs.PR_TITLE }}" -b ""