name: Lint

on:
  push:
  pull_request:
    branches: [ main, dev, release/* ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install black isort
      - name: isort
        run: |
          isort --check-only --diff --quiet .
      - name: black
        run: |
          black --check --diff --quiet --skip-magic-trailing-comma .