name: Scheduled Update
on:
  schedule:
    - cron: '0 11 10-20 * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get next version
      id: get_version
      run: |
        echo "VERSION=`date -d "$(date '+%Y%m01') 1 month ago" "+%Y.%m"`.0" >> $GITHUB_OUTPUT
    - name: Create new branch
      run: |
        git checkout -b release/${{ steps.get_version.outputs.VERSION }} origin/main
        git branch -vv
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install poetry
        poetry install
    - name: Crawl
      run: |
        poetry run python -m src.economy_watchers_survey.crawl
        poetry run python -m src.economy_watchers_survey.create_json
    - name: Diff
      id: diff
      run: |
        git add -N .
        git diff --name-only --exit-code
      continue-on-error: true
    - name: Commit & Push
      run: |
        set -x
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit --author='GitHub Actions <action@github.com>' -m 'Add ${{ steps.get_version.outputs.VERSION }} data'
        git pull
        git push origin release/${{ steps.get_version.outputs.VERSION }}
      if: steps.diff.outcome == 'failure'
        