name: Scheduled Update
on:
  schedule:
    - cron: '0 11 10-20 * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get next version
      id: get_version
      run: |
        echo "VERSION=`date -d "$(date '+%Y%m01') 1 month ago" "+%Y.%m"`.0" >> $GITHUB_OUTPUT
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install poetry
        poetry install
    - name: Crawl
      run: |
        poetry run python -m src.economy_watchers_survey.crawl
        poetry run python -m src.economy_watchers_survey.create_json
    - name: Diff
      id: diff
      run: |
        git add -N .
        git diff --name-only --exit-code
      continue-on-error: true
    - name: Make PR
      uses: peter-evans/create-pull-request@v5
      with:
        title: Add ${{ steps.get_version.outputs.VERSION }} data
        branch: release/${{ steps.get_version.outputs.VERSION }}
        base: main
        commit-message: Add ${{ steps.get_version.outputs.VERSION }} data
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      if: steps.diff.outcome == 'failure'
        